package sauce

const (
	DataTypeNone uint8 = iota
	DataTypeCharacter
	DataTypeBitmap
	DataTypeVector
	DataTypeAudio
	DataTypeBinaryText
	DataTypeXBIN
	DataTypeArchive
	DataTypeExecutable
)

var (
	DataType = map[uint8]string{
		DataTypeNone:       "None",
		DataTypeCharacter:  "Character",
		DataTypeBitmap:     "Bitmap",
		DataTypeVector:     "Vector",
		DataTypeAudio:      "Audio",
		DataTypeBinaryText: "BinaryText",
		DataTypeXBIN:       "XBin",
		DataTypeArchive:    "Archive",
		DataTypeExecutable: "Executable",
	}
	FileType = map[uint8]map[uint8]string{
		DataTypeCharacter: map[uint8]string{
			0: "ASCII",
			1: "ANSi",
			2: "ANSiMation",
			3: "RIP script",
			4: "PCBoard",
			5: "Avatar",
			6: "HTML",
			7: "Source",
			8: "Tundradraw",
		},
		DataTypeBitmap: map[uint8]string{
			0:  "GIF",
			1:  "PCX",
			2:  "LBM/FF",
			3:  "TGA",
			4:  "FLI",
			5:  "FLC",
			6:  "BMP",
			7:  "GL",
			8:  "DL",
			9:  "WPG",
			10: "PNG",
			11: "JPG",
			12: "MPG",
			13: "AVI",
		},
		DataTypeVector: map[uint8]string{
			0: "DXF",
			1: "DWG",
			2: "WPG",
			3: "3DS",
		},
		DataTypeAudio: map[uint8]string{
			0:  "MOD",
			1:  "669",
			2:  "STM",
			3:  "S3M",
			4:  "MTM",
			5:  "FAR",
			6:  "ULT",
			7:  "AMF",
			8:  "DMF",
			9:  "OKT",
			10: "ROL",
			11: "CMF",
			12: "MID",
			13: "SADT",
			14: "VOC",
			15: "WAV",
			16: "SMP8",
			17: "SMP8S",
			18: "SMP16",
			19: "SMP16S",
			20: "PATCH8",
			21: "PATCH16",
			22: "XM",
			23: "HSC",
			24: "IT",
		},
		DataTypeArchive: map[uint8]string{
			0: "ZIP",
			1: "ARJ",
			2: "LZH",
			3: "ARC",
			4: "TAR",
			5: "ZOO",
			6: "RAR",
			7: "UC2",
			8: "PAK",
			9: "SQZ",
		},
	}
	MimeType = map[uint8]map[uint8]string{
		DataTypeCharacter: map[uint8]string{
			0: "text/plain",
			1: "text/plain",
			2: "text/plain",
			3: "image/x-rip",
			4: "text/plain",
			5: "image/x-avatar",
			6: "text/html",
			7: "text/plain",
			8: "image/x-tnd",
		},
		DataTypeBitmap: map[uint8]string{
			0:  "image/gif",
			1:  "image/pcx",
			2:  "image/lbm",
			3:  "image/tga",
			4:  "video/fli",
			5:  "video/flc",
			6:  "image/bmp",
			7:  "video/x-gl",
			8:  "video/x-dl",
			9:  "image/wpg",
			10: "image/png",
			11: "image/jpeg",
			12: "video/mpeg",
			13: "video/x-msvideo",
		},
		DataTypeVector: map[uint8]string{
			0: "image/vnd.dxf",
			1: "image/vnd.dwg",
			2: "image/vnd.wpg",
			3: "image/x-3ds",
		},
		DataTypeAudio: map[uint8]string{
			0:  "Audio/x-mod",
			1:  "Audio/x-mod",
			2:  "Audio/x-mod",
			3:  "Audio/x-mod",
			4:  "Audio/x-mod",
			5:  "Audio/x-mod",
			6:  "Audio/x-mod",
			7:  "Audio/x-mod",
			8:  "Audio/x-mod",
			12: "Audio/midi",
			15: "Audio/x-wav",
			16: "SMP8",
			17: "SMP8S",
			18: "SMP16",
			19: "SMP16S",
			20: "PATCH8",
			21: "PATCH16",
			22: "Audio/x-mod",
			23: "Audio/x-mod",
			24: "Audio/x-mod",
		},
		DataTypeArchive: map[uint8]string{
			0: "application/zip",
			1: "application/arj",
			2: "application/x-lzh",
			3: "application/x-arc",
			4: "application/x-tar",
			5: "application/x-zoo",
			6: "application/rar",
			7: "application/x-uc2",
			8: "application/x-pak",
			9: "applicaiton/x-sqz",
		},
	}
)
